apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # wartości zakodowane w Base64
  # taskuser  -> echo -n "taskuser"  | base64
  POSTGRES_USER: dGFza3VzZXI=
  # password123 -> echo -n "password123" | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
