apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  # ClusterIP - Service dostępny tylko wewnątrz klastra
  # backend łączy się z bazą przez tę nazwę jako adres DNS
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
